#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : my-book  # The title of the book. Will be placed in the left navbar.
author                      : Nicolae Cleju  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "old/**"]
# Auto-exclude files not in the toc
only_build_toc_files        : false

# Information about where the book exists on the web
repository:
  url                       : https://github.com/nikcleju/JupyBook  # Online location of your book
  #path_to_book             : .       # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub (e.g., https://mybinder.org)
  thebe        : true

#===================================

# Nic:
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    mathjax3_config:
      tex:
        macros:
          # "N": "\\mathbb{N}"
          # "floor": ["\\lfloor#1\\rfloor", 1]
          # "bmat" : ["\\left[\\begin{array}"]
          # "emat" : ["\\end{array}\\right]"]
          "snII":  ["#1: \\left( \\begin{matrix} {#2} & {#4} \\\\ #3 & #5 \\end{matrix} \\right)",5]
          "snIII": ["#1: \\left( \\begin{matrix} {#2} & {#4} & {#6} \\\\ #3 & #5 & #7 \\end{matrix} \\right)", 7]
          "snIV":  ["#1: \\left( \\begin{matrix} {#2} & {#4} & {#6} & {#8} \\\\ #3 & #5 & #7 & #9 \\end{matrix} \\right)", 9]
          "sII":   ["#1: \\left( \\begin{matrix} s_1 & s_2 \\\\ #2 & #3 \\end{matrix} \\right)", 3]
          "sIII":  ["#1: \\left( \\begin{matrix} s_1 & s_2 & s_3 \\\\ #2 & #3 & #4 \\end{matrix} \\right)", 4]
          "sIV":   ["#1: \\left( \\begin{matrix} s_1 & s_2 & s_3 & s_4 \\\\ #2 & #3 & #4 & #5 \\end{matrix} \\right)", 5]
          "sV":    ["#1: \\left( \\begin{matrix} s_1 & s_2 & s_3 & s_4 & s_5 \\\\ #2 & #3 & #4 & #5 & #6 \\end{matrix} \\right)", 6]
          "sVI":   ["#1: \\left( \\begin{matrix} s_1 & s_2 & s_3 & s_4 & s_5 & s_6 \\\\ #2 & #3 & #4 & #5 & #6 & #7 \\end{matrix} \\right)", 7]
          "sVII":  ["#1: \\left( \\begin{matrix} s_1 & s_2 & s_3 & s_4 & s_5 & s_6 & s_7 \\\\ #2 & #3 & #4 & #5 & #6 & #7 & #8 \\end{matrix} \\right)", 9]
          "sVIII": ["#1: \\left( \\begin{matrix} s_1 & s_2 & s_3 & s_4 & s_5 & s_6 & s_7 & s_8\\\\ #2 & #3 & #4 & #5 & #6 & #7 & #8 & #9 \\end{matrix} \\right)", 9]
          "fIoII":   ["\\frac{1}{2}"]
          "fIoIII":  ["\\frac{1}{3}"]
          "fIoIV":   ["\\frac{1}{4}"]
          "fIoV":    ["\\frac{1}{5}"]
          "fIoVI":   ["\\frac{1}{6}"]
          "fIoVII":  ["\\frac{1}{7}"]
          "fIoVIII": ["\\frac{1}{8}"]
